# https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/

name: Test

on:
  push

jobs:
  # ------------------------
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          echo "versions=[1,2,3]" >> $GITHUB_OUTPUT
  # ------------------------
  my_echo:
    runs-on: ubuntu-latest
    needs:
      - say_hello
    steps:
      - name: Echo previous outputs
        run: echo "${{ toJSON(needs.say_hello.outputs) }}"
  # ------------------------
  my_matrix:
    runs-on: ubuntu-latest
    needs:
      - my_echo
      - say_hello
    strategy:
      matrix:
        version: ${{ fromJSON(needs.say_hello.outputs.versions) }}
    steps:
      - name: Matrix => ${{ matrix.version}})
        run: |
          echo ${{ matrix.version }}
