# Based on https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/

name: Test

on:
  push

jobs:
  # ------------------------
  select_pylint_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

# https://pypi.org/pypi/pylint/json

      - name: Generate Matrix
        id: generate-matrix
        run: |
          echo "versions=['2.13.9','2.14.5']" >> $GITHUB_OUTPUT


  # ------------------------
  # my_echo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - select_pylint_versions
  #   steps:
  #     - name: Echo previous outputs
  #       run: echo "${{ toJSON(needs.select_pylint_versions.outputs) }}"
  # ------------------------
  test_pylint_compatibility:
    runs-on: ubuntu-latest
    needs:
      # - my_echo
      - select_pylint_versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.select_pylint_versions.outputs.versions) }}
    steps:
      - name: Matrix => ${{ matrix.version}})
        run: |
          echo ${{ matrix.version }}
