# Based on https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/

name: Test

on:
  push

jobs:
  # ------------------------
  select_pytest_versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.versions }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          echo "versions=[1,2,3]" >> $GITHUB_OUTPUT
  # ------------------------
  # my_echo:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - select_pytest_versions
  #   steps:
  #     - name: Echo previous outputs
  #       run: echo "${{ toJSON(needs.select_pytest_versions.outputs) }}"
  # ------------------------
  test_pytest_compatibility:
    runs-on: ubuntu-latest
    needs:
      # - my_echo
      - select_pytest_versions
    strategy:
      matrix:
        version: ${{ fromJSON(needs.select_pytest_versions.outputs.versions) }}
    steps:
      - name: Matrix => ${{ matrix.version}})
        run: |
          echo ${{ matrix.version }}
